### ISSUE TITLE
Please comment here!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/ballin-octo-boo#3]
Thanks.

**Comment by lavinzhang** [comment]
1st?

**Comment by jrevans** [comment]
no comment

**Comment by IbraheemYSaleh** [comment]
:banana:

**Comment by nameche** [comment]
commenting...

**Comment by lcampos71** [comment]
comment

**Comment by CoderRyan800** [comment]
Just want to become more familiar with the Github workflow.

**Comment by greenplayer2** [comment]
...

**Comment by ashamilian** [comment]
I would like to learn how to merge changes

**Comment by loriNakamura** [comment]
More familiarity with the cmd line

**Comment by mckelveyjw** [comment]
Nice weather for GITting.

**Comment by rpuncel** [comment]
cherry-picking

**Comment by carl-potts** [comment]
learn more about merging and conflict changes

**Comment by rhug** [comment]
kind of slow moving here

**Comment by lizreal** [comment]
:+1:

**Comment by mdemore** [comment]
Here I am

**Comment by ljuster** [comment]
I HAVE A MAJOR ISSUE.
- [ ] yes she does
- [ ] maybe
- [ ] nah.

**Comment by maytran** [comment]
commented

**Comment by pwolgast** [comment]
Creating new repos prepends a dash (-) to my repo name and the shell doesn't like that!

**Comment by kmunsell** [comment]
check

**Comment by hockeytish** [comment]
can keep up is my issue, my friend next to me has no github and we are sharing.

**Comment by aruty** [comment]
test
