### ISSUE TITLE
Differences between Enterprise git (JPLGitHub) and free GitHub

### ISSUE THREAD

**Issue by lavinzhang** [githubteacher/ballin-octo-boo#6]
Please describe which features are free and paid for. Thanks!

**Comment by crichID** [comment]
@lavinzhang we actually work hard to maintain feature parity between GitHub.com and GitHub Enterprise. However, you may see some slight differences based on the version of GHE you are on. I will do some additional research on your version and see if I can get you a list of updates introduced in the more recent versions!

**Comment by crichID** [comment]
@lavinzhang JPL is currently on version 2.2.3. I think you will find the differences between 2.2.3 and .com to be very subtle, but you can get more information in the release notes [here](https://enterprise.github.com/releases)

**Comment by lavinzhang** [comment]
Thanks for the link.
